-- 7. 聊天消息落库（chat-ws-service，见 docs/plans/chat-persistence-plan.md）
-- 与 apps/chat-ws-service/src/migrations/20261007_create_chat_messages.sql 逐字节一致
BEGIN;
CREATE TABLE IF NOT EXISTS chat_messages (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  msg_id      UUID NOT NULL,
  room_id     VARCHAR(50) NOT NULL,
  sender_id   UUID NOT NULL,                 -- JWT sub = users.id(UUID)，JOIN 免 cast（C2）
  sender_name VARCHAR(50) NOT NULL,
  is_teacher  BOOLEAN NOT NULL DEFAULT FALSE,
  content     VARCHAR(200) NOT NULL,
  msg_type    SMALLINT NOT NULL DEFAULT 1,
  mentions    JSONB,                          -- NULL=无此字段
  extra       JSONB,                          -- 定死结构，见 §4.1
  created_at  TIMESTAMPTZ NOT NULL            -- 无默认值：缺 time 的重放消息走应用层回退+日志，禁静默 NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS UQ_chat_messages_msg_id    ON chat_messages (msg_id);
CREATE INDEX        IF NOT EXISTS IDX_chat_messages_room_time ON chat_messages (room_id, created_at DESC, id DESC);
COMMIT;
