image: node:24

stages:
  - checks

checks:
  stage: checks
  before_script:
    - corepack enable
    - corepack prepare pnpm@10.28.2 --activate
    - pnpm install --frozen-lockfile
  script:
    - pnpm turbo run lint typecheck test
  only:
    - branches
